################################################################################
# File name: vivado_wc_pre.tcl
# Purpose  : This is an internal file that is auto generated by Vivado to source
#            the user tcl file.
################################################################################
open_project "D:/Documents/HDL/RV32/RV32.xpr"
set rc [catch {
  source -notrace "C:/Users/lukja/AppData/Roaming/Xilinx/Vivado/compile.tcl"
} result]
if {$rc} {
  puts "$result"
  puts "ERROR: Script failed:\"C:/Users/lukja/AppData/Roaming/Xilinx/Vivado/compile.tcl\""
}
close_project
